services:
  ejercicio1:
    build:
      context: .
      dockerfile: Dockerfile  
    image: prueba_frogtek:0.0.1  
    container_name: prueba_frogtek_ejercicio1  
    command: python3 /opt/src/ejercicios/ejercicio1/ejercicio1_launcher.py --text_string "En el año 2010 España ganó el 1er mundial de fútbol de su historia"

  ejercicio2:
    build:
      context: .
      dockerfile: Dockerfile  
    image: prueba_frogtek:0.0.1  
    container_name: prueba_frogtek_ejercicio2
    command: python3 /opt/src/ejercicios/ejercicio2/ejercicio2_launcher.py --ip "127.0.012.123"

  ejercicio3:
    build:
      context: .
      dockerfile: Dockerfile  
    image: prueba_frogtek:0.0.1  
    volumes:
      - ./src/ejercicios/ejercicio3:/opt/src/ejercicios/ejercicio3
    container_name: prueba_frogtek_ejercicio3
    command: python3 /opt/src/ejercicios/ejercicio3/ejercicio3_launcher.py

  ejercicio3_custom_file:
    build:
      context: .
      dockerfile: Dockerfile  
    image: prueba_frogtek:0.0.1  
    volumes:
      - ./src/ext_files:/opt/src/ext_files
    container_name: prueba_frogtek_ejercicio3_custom_file
    command: python3 /opt/src/ejercicios/ejercicio3/ejercicio3_launcher.py --file_path "/opt/src/ext_files/prueba_ciudades.txt"

  tests:
    build:
      context: .
      dockerfile: Dockerfile  
    image: prueba_frogtek:0.0.1  
    container_name: prueba_frogtek_tests
    command: pytest -v
