name: Linting

# Define cuándo se ejecutará este workflow
on:
  push:  # Se ejecutará en cualquier push en cualquier rama
  pull_request:
    branches:
      - main  # Se ejecutará en cualquier pull request, independientemente de la rama

jobs:
  lint:
    runs-on: ubuntu-latest  # El entorno en el que correrán los linters
    steps:
      - name: Checkout code  # Paso para clonar el repositorio
        uses: actions/checkout@v3

      - name: Set up Python  # Paso para configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.5'  # Define la versión de Python

      - name: Install dependencies  # Instalar dependencias desde requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-lint.txt  # Instala las dependencias

      - name: Run Flake8  # Ejecutar Flake8
        run: |
          flake8 .  # Ejecuta Flake8 en el directorio actual

      - name: Run Black check  # Ejecutar Black en modo de verificación
        run: |
          black --check .  # Ejecuta Black en modo de verificación

      - name: Run isort check  # Ejecutar isort en modo de verificación
        run: |
          isort --check-only .  # Ejecuta isort en modo de verificación

