name: Run Tests

# Definir cuándo se ejecutará el workflow:
on:
  push:  # Se ejecuta en cada push
  pull_request:  # Se ejecuta en cada pull request

jobs:
  test:
    runs-on: ubuntu-latest  # Elige un entorno de ejecución

    env:
      GITHUB_ACTIONS: "github_actions" 

    steps:
      # Clonar el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar Python en el entorno
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.5'  # Define la versión de Python que necesitas

      # Instalar las dependencias desde requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      # Establecer el PYTHONPATH para incluir el directorio 'src'
      - name: Set PYTHONPATH
        run: |
          export PYTHONPATH="$PYTHONPATH:$(pwd)/src"
          echo "PYTHONPATH: $PYTHONPATH"
        shell: bash

      # Ejecutar los tests con pytest
      - name: Run tests
        working-directory: ./src  # Cambia el directorio de trabajo a src
        run: |
          export PYTHONPATH="$PYTHONPATH:$(pwd)"  # Establecer PYTHONPATH
          pytest  # Ejecutar pytest
        shell: bash
